### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Trowic** [greg-dubrow/greg_dubrow_io#1]
Hi,

I visited your website and had to changes the settings of non essentials cookies.
According to the GDPR, these should be opt-out by default and not opt-in.

**Comment by greg-dubrow** [comment]
Yes, I've tried a few times to alter the quarto.yml per the quarto guidelines but it's not working as it should based on their documentation. The default should include a decline option, but it's not showing up. See this thread for what the cookie consent window should look like based on my yaml
https://github.com/quarto-dev/quarto-cli/discussions/5958

I'm exploring an alternative option that someone else used (noted in that thread) because of the same issue but it involves some .js additions that are a bit advanced for me, so might take some time to implement. But thanks for letting me know.

**Comment by greg-dubrow** [comment]
Needed to add or redo a post for changes to yaml to take effect. Now compliant.
